language: ruby
script: "bundle exec jekyll build"

rvm:
- 2.1.7

branches:
  only:
  - master
  #- gh-pages     # test the gh-pages branch
  #- /pages-(.*)/ # test every branch which starts with "pages-"

# env:
#   global:
#   - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
#
# sudo: false # route your build to the container-based infrastructure for a faster build
