title: Rokma
locale: en_US
description: "Communication Design and Media Engineering"
shout_description: "Flexible Communication Design for small companies. Imagine. Plan. Produce. Launch. And also just consulting!"
logo: 01.jpg
tagline: 'empowers small enterprises'
tagline_short: 'empowers'
tagline_plus: 'building reputation'

baseurl: ""
url: http://rokma.com

version: 16.2.0
version_details: 'open cleaned source'

# Outputting
permalink:   /:categories/:title/
relative_permalinks: false
paginate: 15
paginate_path: "index/:num/"

# Setup
sass:
  sass_dir: _sass
  style: :compressed
  # style: :expanded



markdown: kramdown

owner:
  name: Rokma
  avatar: o-avatar.jpg
  email: me@rokma.com
  web: http://rokma.com
  twitter: rokmatwit
  facebook: rokmaphotography
  github: toybreaker
  linkedin: rokma
  soundcloud: rokma
  googleplus: rokma

google:
  analytics: UA-1305149-1
  verify: google32e66f1a5601ec40
  ad-client:
  ad-slot:


gems: [github-pages, jekyll-feed, jekyll-sitemap, jekyll-seo-tag, html-proofer]

exclude: [vendor]

exclude: [".htaccess", "gulpfile.js", "package.json", "Gemfile", "Gemfile.lock", "LICENSE", "Icon"]
