title: Rokma
locale: en
description: "Communication Design and production."
shout_description: "Flexible Communication Design for small companies. Imagine > Plan > Produce > Launch. And also just consulting!"
logo: 01.jpg
tagline: 'empowers small enterprises'
tagline_short: 'empowers'
tagline_plus: 'building reputation'

baseurl: ""
url: https://rokma.com

version: 16.7.0
version_details: 'netli-firefly'

# Outputting
permalink:   /:categories/:title/
relative_permalinks: false
paginate: 15
paginate_path: "index/:num/"

# Setup
sass:
  sass_dir: _sass
  style: :compressed
  # style: :expanded

markdown: kramdown

owner:
  name: Rokma
  avatar: o-avatar.jpg
  email: rokmabox@gmail.com
  web: https://rokma.com
  twitter: rokmatwit
  facebook: rokmaphotography
  github: toybreaker
  linkedin: rokma
  soundcloud: rokma
  googleplus: rokma

producer: https://www.junglestar.org

google:
  analytics: UA-1305149-1
  verify: google32e66f1a5601ec40

plugins:
 - jekyll-seo-tag
 - jekyll-redirect-from
 - jekyll-sitemap
 - jekyll-paginate

exclude:
  - Gemfile.lock
  - node_modules
  - package-lock.json
  - Gemfile
  - rakefile
  - gulpfile.js
