version:             18.2.0
title:               Rokma
locale:              en
description:         "Communication Design and production."
shout_description:   "Flexible Communication Design for small companies. Imagine > Plan > Produce > Launch. And also just consulting!"
logo:                01.jpg
tagline:             'empowers small enterprises'
tagline_short:       'empowers'
tagline_plus:        'building reputation'

baseurl:             ""
url:                 https://rokma.com

version_details:     'ScrollToFineArtPrints'

# Outputting
permalink:           /:categories/:title/
relative_permalinks: false
paginate:            9
paginate_path:       "index/:num/"

# Setup
sass:
  sass_dir:          _sass
  style:             :compressed
  # style:           :expanded

markdown:            kramdown

owner:
  name:              Rokma
  avatar:            o-avatar.jpg
  email:             rokmabox@gmail.com
  web:               https://rokma.com
  twitter:           rokmatwit
  facebook:          rokmaphotography
  instagram:         rokmaphotography
  github:            toybreaker
  linkedin:          rokma
  soundcloud:        rokma
  googleplus:        rokma

producer:            https://www.junglestar.org

google:
  analytics:         UA-1305149-1
  verify:            google32e66f1a5601ec40

plugins:
 - jekyll-seo-tag
 - jekyll-redirect-from
 - jekyll-sitemap
 - jekyll-paginate
 - html-proofer

exclude:
  - vendor
  - Gemfile.lock
  - Gemfile
