title: Rokma
locale: en_US
description: "Communication Design and production."
shout_description: "Flexible Communication Design for small companies. Imagine > Plan > Produce > Launch. And also just consulting!"
logo: 01.jpg
tagline: 'empowers small enterprises'
tagline_short: 'empowers'
tagline_plus: 'building reputation'

baseurl: ""
url: https://rokma.com

version: 16.6.0
version_details: 'netlify now fly'

# Outputting
permalink:   /:categories/:title/
relative_permalinks: false
paginate: 15
paginate_path: "index/:num/"

# Setup
sass:
  sass_dir: _sass
  style: :compressed
  # style: :expanded

markdown: kramdown

owner:
  name: Rokma
  avatar: o-avatar.jpg
  email: rokmabox@gmail.com
  web: https://rokma.com
  twitter: rokmatwit
  facebook: rokmaphotography
  github: toybreaker
  linkedin: rokma
  soundcloud: rokma
  googleplus: rokma

producer: https://www.junglestar.org

google:
  analytics: UA-1305149-1
  verify: google32e66f1a5601ec40

plugins: [github-pages, jekyll-feed, jekyll-sitemap, jekyll-seo-tag, html-proofer]

exclude: ["gulpfile.js", "package.json", "Gemfile.lock", "LICENSE", "Icon"]

exclude: [vendor]
